### ISSUE TITLE
Ecological Scaling and In Game Config 

### ISSUE THREAD

**Issue by ReportBot9009** [TinyModularThings/UniqueEnchantments#12]
First off, playing Enigmatica 2 Expert and added this to the pack. 

The in game config does not seem to change settings live. I have to restart to see changes. Is this intended?

Also, what does "scale" mean under ecological? Does it mean at level 1 it takes x amount of time and at level 3 it takes x+scale #? 

So my config looks like this:
ecological {
    I:base_cost=22
    I:cost_limit=40
    B:enabled=true
    I:per_level_cost=2
    I:rarity=2
    D:scale=0.01
    I:speed=200
    B:treasure=true

Does scale act as a modifier increasing speed? So, if I want it to scale to much faster, I could change the scale from 0.01 to 1.0 or 2.0? I've tried this in game and it doesn't seem to change anything, requiring a restart. Also, the speed is the only configuration modifier that seems to do anything.

I would love some directions in the config making it easier for lay people like myself to understand what scale, scalar, speed etc. mean pertaining to your mod.

Thanks for the help!

**Comment by Speiger** [comment]
Yes config changes only get applied if you reload stuff (command or game)
Some items require a requipping because otherwise its not detectable that changes happened.

You can look up things in code here.
https://github.com/TinyModularThings/UniqueEnchantments/blob/1.12.2/src/main/java/uniquee/handler/EntityEvents.java#L294

Scale affects how fast the enchantment gets executed, based on the level.
Speed does the same but is a global modifier while scale is level based effect.

Blame @Xaikii for such good names in the variables. (I am worse but I didnt come up with them xD)

**Comment by Xaikii** [comment]
An update on this.
The naming of many variables changed with our next patch.
This should be done now.
I'll leave it open if there are any further confusion.
