### ISSUE TITLE
Weapen of "uniquee:focus_impact", the damage will be reduced to zero when ex high attack speed.

### ISSUE THREAD

**Issue by rtxyd** [TinyModularThings/UniqueEnchantments#21]
When I tested the compatibility of other mods, I found this problem, for weapons enchanted by "focus_impact" with an attack speed higher than a certain value or by increasing the attack speed to a certain value in other ways, it appears to reduce damage, then it can be reduce to zero.

**Comment by Xaikii** [comment]
while it would help if you added the attack speed values you've used, everything seems to work as intended.
Let me explain you:
Focus Impact is an Enchantment for slower weapons.
The formula is: `log10(Level * PercentualBonusDamagePerLvL / AttackSpeed^2)`
Let's say we have a Diamond Axe, Diamond Sword & a Modded Sword with 2.6 Attack Speed.
with the formula we would get the following results on Focus Impact Level 3:
Diamond Axe = 0.49
Diamond Sword = 0.09
Modded Sword = -0.262

The bonus damage of Focus Impact is %-bonus
Therefore the Diamond Axe would get 49% more Damage, the Sword 9%, and the Modded Sword would lose 26.2% of it's damage to the target (or in better words, the target receives -26.2% of the Weapons damage, and because it's negative, it turns into a heal instead)

If the Weapon is too fast for this Enchantment, the Damage could even turn completely into healing.

If you're looking for an Equivalent for Fast Weapon, you should go for "Swift Blade", which is a Treasure Enchantment and can't be received via enchanting (unless you change it in the config).

**Comment by rtxyd** [comment]
the attack speed I've used may be close to the upper limit, may be 10 or higher, besides, I turn on the anti negative damage option of another mod, so it was  just zero damage.

**Comment by rtxyd** [comment]
Got it. Thanks. I just thought it might contribute to damage.

**Comment by Speiger** [comment]
Is this resolved?

**Comment by rtxyd** [comment]
Yes, I may be a little awkward since it worked as intended. @Speiger
