### ISSUE TITLE
Death's Odium health regain issues // balance?

### ISSUE THREAD

**Issue by srwaggon** [TinyModularThings/UniqueEnchantments#28]
A user is reporting that they cannot find the way to undo Death's Odium after a death.

https://discord.com/channels/512339624627011586/570614531655598120/802271988398817350

Their higher level issue is that the curse's effect remains even beyond the scope of the item. Perhaps it would be possible to rework this curse while still keeping the intended punishment.

e.g., While equipped with an item cursed by Death's Odium, the player loses health proportional to the number of deaths they have experienced with the item equipped.

This effectively makes a really great item slowly become more punishing for bad gameplay, as opposed to permanently punishing a player for not having, losing, or breaking a particular cursed item.

**Comment by Xaikii** [comment]
Hey there,

thanks for the report. We're aware of that issue. 
Let me tell you first, that is just a visual bug. After regaining the HP, you'll end up at 19.99 HP due to some issues... and as you dont have 20 or more HP, Minecraft wont display that "missing" Heart.

However after time, more and more report came in for this Curse, and we're planning on including a way to regain those hearts without the Curse being active. We like the way the Curse is right now, and thus wont change the functionality.

Yet we dont know how we want to implement thus Method. As we want this to be accessible in the early game, but still be a pain in the lategame(post-netherite).
If you got an idea, dont hesitate to tell :)

**Comment by srwaggon** [comment]
Issue seems resolved by developers.

If I have any ideas, I'll share them. 😃

**Comment by Speiger** [comment]
@srwaggon you just saw the documentation change because we decided on a new method,
nothing is actually implemented. @Xaikii was just a head of me.

Keeping this open until release. That way you have also a direct notification.

**Comment by Speiger** [comment]
Addressed in latest patch

**Comment by musa18109** [comment]
hey there iam playing roughlike Adventures and Dungeons 2 and i cant enchant the cookie can anyone help me?
