### ISSUE TITLE
Unique enchantments causes game crashes and erases 'library' when used with Enchantment Machine

### ISSUE THREAD

**Issue by AuroraHydroid** [TinyModularThings/UniqueEnchantments#60]
For 1.16.5, when Unique Enchantments is used with Enchantment Machine (url: https://www.curseforge.com/minecraft/mc-mods/enchantment-machine), the game crashes if the enchanter is used (for instance enchanting a book). Additionally, any books that were put into the enchanting 'library' are erased.

UE was found to be the culprit by a process of elimnation. The crash log lies.

[crash-2022-06-09_21.42.04-fml.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/8879807/crash-2022-06-09_21.42.04-fml.txt)
.

**Comment by Xaikii** [comment]
are you sure that's the right file?
that tells me you don't have crafttweaker installed
also pls use pastebin or similar for logs

**Comment by AuroraHydroid** [comment]
Here's the correct crashlog: https://pastebin.com/PXSnVfz8

**Comment by Speiger** [comment]
@AuroraHydroid UE isn't even mentioned in the log and anything we change would trigger UE to be in the logs.

**Comment by AuroraHydroid** [comment]
I'm not sure why it isn't showing in the logs, and that's why this is a frustrating issue.
Here is a crash log with only UE and EM enabled. UE is the only thing that is causing it to crash. If it's not possible to find it on this end, I'll see if EM can find anything.

https://pastebin.com/sq3sNRrr

**Comment by Speiger** [comment]
Yeah found the bug. It is within enchantment machine.
https://github.com/Cheaterpaul/EnchantmentMachine/blob/1.18/src/main/java/de/cheaterpaul/enchantmentmachine/client/gui/screens/inventory/EnchanterScreen.java#L140

Basically what the bug is. Enchantment machine expects the "Color" of the Name to be not null. UE adds icons which are not colored (null) which enchantment machine doesn't account for and crashes.

Yes this is a UE caused, but the bug is not within UE because minecraft clearly defines that "Colors" can be null and the dev didn't account for that.

**Comment by Speiger** [comment]
Opened issue with Enchanting machine since its their bug.

**Comment by AuroraHydroid** [comment]
Thank you very much for your time! I appreciate the expertise.

**Comment by Speiger** [comment]
@AuroraHydroid fix should be out from his side.
