### ISSUE TITLE
[UniqueBase, 1.16.5] Key bind hash map can get negative array bounds crash if world is loaded whilst window not in focus

### ISSUE THREAD

**Issue by NighthowlerStudios** [TinyModularThings/UniqueEnchantments#64]
Only crashes whilst initializing a world in singleplayer, if the window was not in focus whilst it was opening.  Seemingly random and uncommon crash but has happened multiple times now to me.

https://pastebin.com/KM19gk6i

simple protection against negative bounds may or may not work.  it is possible this method needs to tick at a different time as well.  tracelog contains no mention of any other mods nor their mixins so I cannot suspect a conflict.  It might be some awfully nested forge bug with where postClientTick gets fired at a time uniquebase does not expect.

**Comment by Speiger** [comment]
Ok, yeah this is a edge case that might have been slipped.
I look at it the moment i am not rewriting 6 mods at the same time.

**Comment by Speiger** [comment]
By the way the reason this specific crash can happen in fastUtil is,
if the current value being accessed was removed or triggered a rehash of the underlying hashmap, which results in a negative check because fastutil actually caches if a rehash happens in a "temp list" that uses negative values to validate the next index in said temp cache in the iterator.

Sadly this implementation has still some bugs left.

**Comment by Speiger** [comment]
Ok should be fixed now
