### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by Mechint0** [TinyModularThings/UniqueEnchantments#71]
The mod is incompatible with apotheosis and majruszs enchantments 
it crashes when these mods are mixed together with the unique enchantments mod

**Comment by Xaikii** [comment]
Incompat with Apotheosis is already known and looked at

**Comment by Mechint0** [comment]
> Incompat with Apotheosis is already known and looked at

will there be a fix soon or nah?

**Comment by Xaikii** [comment]
This is a mixin error of a feature we do not want to remove, I cant guarantee, but we are looking for a solution

**Comment by Mechint0** [comment]
> 

ok ok thanks for answering my questions

**Comment by Mechint0** [comment]
just found out that it has compatibility issues with other enchant mods

**Comment by Xaikii** [comment]
in what way?

**Comment by Xaikii** [comment]
could you maybe join our [Discord](https://discord.gg/EHpb6JCPkW) to elaborate?

**Comment by Mechint0** [comment]
is the problem with apotheosis fixed yet?

**Comment by Speiger** [comment]
@Mechint0 the Mixin Config has been added to the mod, but the patch isn't out yet.
The release ETA is this week (before the weekend)

**Comment by jimmy06200** [comment]
Hello and is this still an issue ? got the same problem with the enigmatica modpack ?
Thx for your times

**Comment by Xaikii** [comment]
@jimmy06200 
This is an issue that will persist by default, but we added a way to fix it.
Open the "ue" config folder, open "MixinConfig.properties" and turn "common.entity.LivingEntityMixin" to false

**Comment by jimmy06200** [comment]
Thx for the help !! IT Launched  but got that answer from minecraft 

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [uniquebase.mixins.json:common.enchantments.EnchantmentHelperMixin] from phase [DEFAULT] in config [uniquebase.mixins.json] FAILED during APPLY

Feel like i am learning an other language XD 

[crash-2022-12-10_22.07.51-server.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/10200962/crash-2022-12-10_22.07.51-server.txt)

**Comment by Xaikii** [comment]
same thing, just now you also set "common.enchantments.EnchantmentHelperMixin" to false

**Comment by jimmy06200** [comment]
Sadly same crash but new line of cause 

Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("TAIL")] on net/minecraft/world/item/enchantment/EnchantmentHelper::removeApexEnchantments with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44817_(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [PREINJECT Applicator Phase -> uniquebase.mixins.json:common.enchantments.EnchantmentHelperMixin -> Prepare Injections ->  -> handler$bmn000$removeApexEnchantments(ILnet/minecraft/world/item/ItemStack;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V -> Prepare]

Still thank for trying 

[crash-2022-12-10_22.45.54-server.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/10201020/crash-2022-12-10_22.45.54-server.txt)

**Comment by jimmy06200** [comment]
Sorry again =3 did you have the time to check if its my doing for beeing so bad ? or bad luck =s ?

**Comment by rgmoon** [comment]
Same here.

**Comment by Xaikii** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@at("TAIL")] on net/minecraft/world/item/enchantment/EnchantmentHelper::removeApexEnchantments with priority 1000 cannot inject into net/minecraft/world/item/enchantment/EnchantmentHelper::m_44817_(ILnet/minecraft/world/item/ItemStack;Z)Ljava/util/List; merged by shadows.apotheosis.mixin.EnchantmentHelperMixin with priority 1000 [PREINJECT Applicator Phase -> uniquebase.mixins.json:common.enchantments.EnchantmentHelperMixin -> Prepare Injections -> -> handler$bmn000$removeApexEnchantments(ILnet/minecraft/world/item/ItemStack;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/List;)V -> Prepare]

Not reproduceable on my side...
I did receive the LivingEntityMixin issue, but not the EnchantmentHelperMixin issue.

That being said, it's the same step as before, go into the "MixinConfig.properties" and set "common.enchantment.EnchantmentHelperMixin" to false

**Comment by jimmy06200** [comment]
Sadly still the same ...

**Comment by Xaikii** [comment]
saying "sadly still the same" doesnt help me to help you...
send your logs, use websites like pastebin to do so

**Comment by jimmy06200** [comment]
Here you go for the lastest logs and crash 

[crash-2022-12-19_22.01.47-client.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/10263181/crash-2022-12-19_22.01.47-client.txt)

[latest.log](https://github.com/TinyModularThings/UniqueEnchantments/files/10263182/latest.log)

Thank again !!!

**Comment by Xaikii** [comment]
> uniquebase.mixins.json:common.enchantments.EnchantmentHelperMixin

It says you didnt disable the EnchantmentHelperMixin

**Comment by jimmy06200** [comment]
In config i've got that when you ask me to change the first time but

common.enchantment.EnchantmentHelperMixin=false

common.entity.LivingEntityMixin=false

I don't know what to say much ? 

But ive still have the same error

**Comment by Xaikii** [comment]
are you playing a custom modpack or a public modpack?
Did you add UE yourself to it, or was it in there by default?

**Comment by jimmy06200** [comment]
I use enigmatica 9 public modpack and try to add your mod , it boot to create The UE config in minecraft and i modifie it

**Comment by Xaikii** [comment]
ok, I'll look into it when I have time

**Comment by jimmy06200** [comment]
Thank a lot !! =3

**Comment by Xaikii** [comment]
Good and Bad news.
I think I found the issue,
but it's a bigger problem and that fix wont come soon, next year earliest.

**Comment by jimmy06200** [comment]
Thx a lot =3 no worries for the times, i dont know anything about coding and that stuff but i can only apreciate everyone work =3.
So thx again for the extra work you put for me =3
