### ISSUE TITLE
Remove texture

### ISSUE THREAD

**Issue by TreeFall1** [TinyModularThings/UniqueEnchantments#77]
How i can remove new enchantments textures? I like vanilla more.

**Comment by Xaikii** [comment]
go to into the UEBase.toml
set "Enchanted Glint" to true
and "Enable Item Coloring" to false
lastly you just need to add a Resourcepack which one contains the old Enchanted Book ~~Texture~~ edit: Model file [below you find an example for 1.19]

**Comment by TreeFall1** [comment]
Its doesnt work(

**Comment by Dale125** [comment]
Yup, it's not working.

**Comment by Deepfriedyag** [comment]
@Xaikii The auto enabled GODAWFUL textures that you can't turn off is the sole reason I won't use this mod ever. JUST PLEASE MAKE IT A CONFIG OPTION. It looked like it had really cool enchants until I saw the textures and it took me 20 mins to figure out I can't turn it off.

**Comment by Zarchyar** [comment]
@Deepfriedyag 
You need a texture pack that replaces the model in addition to the config changes to revert the texture.
Such as this example one that only changes that(file formatted for 1.19.1 but should work for most MC versions).

[enchantedbook.zip](https://github.com/user-attachments/files/16970491/enchantedbook.zip)

**Comment by Deepfriedyag** [comment]
> @Deepfriedyag You need a texture pack that replaces the model in addition to the config changes to revert the texture. Such as this example one that only changes that(file formatted for 1.19.1 but should work for most MC versions).
> 
> [enchantedbook.zip](https://github.com/user-attachments/files/16970491/enchantedbook.zip)

I want to use another mod for my enchanted book textures (nekos enchanted books) and this mod simply clashes with that.

**Comment by Zarchyar** [comment]
![image](https://github.com/user-attachments/assets/0efb8dea-b7a3-4f3c-97fc-5aa68d3f62fb)

![image](https://github.com/user-attachments/assets/e6cf5899-fef8-4ec6-81ee-b45ff078e472)

**Comment by Zarchyar** [comment]
@Deepfriedyag 
then you would need to replace the model with their model (this is the 1.19 file)
https://github.com/infernalstudios/Nekos-Enchanted-Books/blob/main/1.19/src/generated/resources/assets/minecraft/models/item/enchanted_book.json

**Comment by Zarchyar** [comment]
[nekoenchantedbook.zip](https://github.com/user-attachments/files/16970675/nekoenchantedbook.zip)
![image](https://github.com/user-attachments/assets/d7fb4394-9434-4bab-99cf-3f714805a927)

**Comment by Deepfriedyag** [comment]
That worked. Atleast you were helpful and quick to respond altough I still don't understand why I need to commit learning wizardry just to turn off the book textures I feel like an option could've easily been implemented in the config

**Comment by Speiger** [comment]
@Deepfriedyag Xaikii was not able to write an answer.
And I was asked not to answer because he knows that I don't mind give the same energy back as we received.

So STFU and leave.

**Comment by Xaikii** [comment]
now that I have the time to write, I want to first apologize @TreeFall1 and @Dale125, I have not received a notification about a message which cause this issue to be out of my vision that was a persistent issue.
Next up I would like to apologize for the mistake, it indeed was the model that needed to be changed, I will correct that in the original answer. Thanks again to @Zarchyar for replying while I couldn't.

Now to the more pressing matter, being @Deepfriedyag.
If that is how you ask for changes, then please get the fuck out of this community I really don't want you here, I try to help where I can and include our community in both design and balance. 
Everybody has a different level of skillset in various areas, and we try to make stuff as customizable as possible, with a varying skillset that also includes areas where one is not proficient. Making that thing a config was simply not within our capabilities at that point. Since then we have tried to improve on it with limited success, and frankly I still have no good idea how to make that thing a config while keeping it vanilla style implementation.
And when you're given instructions on how to fix it, and proceeding to call it ` still don't understand why I need to commit learning wizardry just to turn off the book textures` for something that is basic resource pack work, and I REALLY mean basic... you might not be fit to behave like the entitled brat as you do.
Not everybody has to like our products, and that is fine, at least I specifically create "niche" products, I don't want to target everyone, but I want stuff to be accessible to everyone. If you don't like it, so be it. But behaving as if we owe you a tailor made product for free, while you do nothing but yelling, I don't know dude.
Let alone that we also have a Discord which we're actively watching for questions and feedback, you also seemingly didn't manage to find, yet 480 other Users did manage to find it and give their feedback or want news.

In other news, we are working on a new Book Palette, basically books v3, which are more in the vanilla style.
