### ISSUE TITLE
Unknown crash on start-up

### ISSUE THREAD

**Issue by Juicylene** [TinyModularThings/UniqueEnchantments#90]
Using tl legacy, minecraft version 1.19.2 forge 43.2.19
![image](https://github.com/TinyModularThings/UniqueEnchantments/assets/88633668/c01a4dd1-f4f3-4444-9b06-84662aee4bb4)

Crash log:
[tl-logger11525789278315869676.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/12090536/tl-logger11525789278315869676.txt)

**Comment by Speiger** [comment]
@Juicylene balance anvil mod is incompatible since we integrated the functionality iirc.

Difference in UEs implementation:
If it says: 30 levels, you require 30 levels to be present, but it only consumes 30 levels of XP instead of removing 30 levels.
So if you are level 60 you will barely notice it.
(Also there is configs to modify if you need more or less levels of XP of what the anvil says)

Also same functionality is implemented into the enchantment table.

**Comment by Juicylene** [comment]
ooooooh thx a lot for the help
