### ISSUE TITLE
[1.16.5] Potential Berserker Bug

### ISSUE THREAD

**Issue by nightlightest** [TinyModularThings/UniqueEnchantments#97]
The Transcended version of the Berserker enchant makes player's maximum HP halved. This results in a constant attempt to regenerate HP, even when the player is at full health. As a consequence, the player rapidly consumes food, depleting it within seconds, even when standing still and not performing any actions. After reviewing the documentation, I don't think that this behavior is intended. Mod version - 2.3.3.1

**Comment by Xaikii** [comment]
this is indirectly intentional.
it is exactly as you described, a constant attempt to regen life which consumes hunger.

admittedly, first it was unintentional, but then we saw it decided to keep it.
There would be ways to prevent that, but we decided not to.

With the next update we're doing, which is a big one, the overall documentation will be massively overhauled.
